services:
  # OpenWrt Compiler
  openwrtcompiler:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes: 
      # - ./build/:/host/
      # - ./includes/:/host/includes/
      # - ./custom/:/host/custom/
      # - ./output/:/host/output/
      # - ./docker/entrypoint.sh:/startup.sh
      # - ./config/.config:/host/.config
      # - ./config/feeds.conf:/host/feeds.conf
      # - ./config/feeds.conf.default:/host/feeds.conf.default

        - ../docker/entrypoint.sh:/startup.sh
        - ../submodules/openwrt:/host/
        - ../submodules/toolchain:/host/feed-toolchain-3005/
        - ../config/.config:/host/.config
        - ../config/feeds.conf:/host/feeds.conf
        - ../out/:/host/output/
        - ../custom/:/custom/
    container_name: openwrtcompiler
    working_dir: /host/
    entrypoint: ["/bin/sh", "/startup.sh"]
    env_file:
      - ../env/.git_credentials.env
    environment:
      - OUTPUT_DIR=/host/output
      - ROOT_DIR=/host/staging_dir/target-mipsel-openwrt-linux-musl_musl/root-ramips
      - OUTPUT_DIR=/host/output
          
  # http server to serve the output files to be downloaded for testing.
  httpserver:
    image: httpd:alpine3.18
    container_name: httpserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./out/:/usr/local/apache2/htdocs/"