FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --force-yes --no-install-recommends \
build-essential clang flex bison g++ gawk \
gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget \
ccache ecj fastjar file g++ gawk java-propose-classpath libelf-dev libncurses5-dev \
libncursesw5-dev  python2.7-dev python3 \
python3-dev subversion time xsltproc 